### ISSUE TITLE
Missing header in solution csv files

### ISSUE THREAD

**Issue by mustafasaydam** [sametbirol/BLG223E_ITU_2024_FALL#2]
<img width="699" alt="image" src="https://github.com/sametbirol/BLG223E_ITU_2024_FALL/assets/98849333/b8fad148-d508-4555-bb91-e0766c3c119e">

**Comment by sametbirol** [comment]
This was reviewed promptly after the release of Ninova test cases, and both solutions (with and without a header) have been confirmed as acceptable, as indicated by the assistant in the [Homework 1 info](https://github.com/sametbirol/BLG223E_ITU_2024_FALL#homework-1-related-info). Please remember to run `git pull` or, if necessary, delete the folder and perform a `git clone` to ensure you have the latest solution.
